name: publish
on:
  push:
    branches:
      - main

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.HUB_TOKEN }} # Use GITHUB_TOKEN instead of HUB_TOKEN

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/raghu261992/hello-docker-gcr-demo:latest
          docker run ghcr.io/raghu261992/hello-docker-gcr-demo:latest
          docker push ghcr.io/raghu261992/hello-docker-gcr-demo:latest
